### ISSUE TITLE
How to setup and use this repo?

### ISSUE THREAD

**Issue by Qind1609** [aws-deepracer/deepsim#2]
Would you mind providing an example of setup and usage of this repo? 
I am confused when using this repo

**Comment by lingjiekong** [comment]
Thanks for your question! 

DeepSim is A Reinforcement Learning Environment Build Toolkit for ROS and Gazebo. DeepSim is a framework which provides customer easy to use toolkits to build simulation application on top of ROS and Gazebo. 

You can read our paper https://arxiv.org/abs/2205.08034 to understand how you can use DeepSim framework to build your own simulation application.

**Comment by Qind1609** [comment]
Yeah, I have read the paper but I think I need a detail instruction or an example project code to understand what i should do with this repo.

**Comment by curieuxjy** [comment]
I'm also looking forward to some brief documentation or instruction.
